### ISSUE TITLE
应该先验证参数是否有效~~~再内部逻辑验证

### ISSUE THREAD

**Issue by CQzhangshuai** [sigoden/openapize#1]
![image](https://user-images.githubusercontent.com/28768888/56946992-65c4b980-6b5e-11e9-9711-75ca86525b2e.png)
应该先验证参数是否有效~~~再内部逻辑验证
@sigoden

**Comment by sigoden** [comment]
validate 比 security 耗费资源，而且 security 中一般不会用到接口请求参数，所以应该先验证权限，再进行参数验证
